"""Initial schema — driven from ORM metadata.

Because the MVP iterates fast, we use ``create_all`` from the ORM metadata
inside a single migration. Later, we'll switch to autogenerated diffs.
"""

from __future__ import annotations

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    from app.db.models import Base

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    from app.db.models import Base

    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
